CREATE TABLE IF NOT EXISTS `claim` (
  `resourcetype` VARCHAR(255) DEFAULT NULL,
  `id` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `type_coding` VARCHAR(255) DEFAULT NULL,
  `use` VARCHAR(255) DEFAULT NULL,
  `patient_reference` VARCHAR(255) DEFAULT NULL,
  `patient_display` VARCHAR(255) DEFAULT NULL,
  `billableperiod_start` VARCHAR(255) DEFAULT NULL,
  `billableperiod_end` VARCHAR(255) DEFAULT NULL,
  `created` VARCHAR(255) DEFAULT NULL,
  `provider_reference` VARCHAR(255) DEFAULT NULL,
  `provider_display` VARCHAR(255) DEFAULT NULL,
  `priority_coding` VARCHAR(255) DEFAULT NULL,
  `facility_reference` VARCHAR(255) DEFAULT NULL,
  `facility_display` VARCHAR(255) DEFAULT NULL,
  `diagnosis` VARCHAR(255) DEFAULT NULL,
  `insurance` VARCHAR(255) DEFAULT NULL,
  `item` VARCHAR(255) DEFAULT NULL,
  `total_value` FLOAT DEFAULT NULL,
  `total_currency` VARCHAR(255) DEFAULT NULL,
  `supportinginfo` VARCHAR(255) DEFAULT NULL,
  `procedure` VARCHAR(255) DEFAULT NULL,
  `prescription_reference` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;